services:
  cpu-load:
    image: pexcn/docker-images:cpu-load
    container_name: cpu-load
    restart: unless-stopped
    network_mode: none
    environment:
      TZ: Asia/Taipei
    command: -p 40:60 -t 00:30-06:30 -d 20% -m 60
