services:
  cpu-load:
    image: pexcn/docker-images:cpu-load
    container_name: cpu-load
    restart: unless-stopped
    network_mode: none
    environment:
      TZ: Asia/Taipei
      PERCENT_RANGE: "40:60"
      TIME_RANGE: "00:30-06:30"
      ACTIVE_SECONDS: "7200"
